java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-DMXA.jar >> DMXA-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUE.jar >> ALUE-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
java -jar Prim-PairHeap-ALUT.jar >> ALUT-PairHeap-Prim.txt
