java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-DMXA.jar >> DMXA-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUE.jar >> ALUE-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
java -jar RR-Fibo-ALUT.jar >> ALUT-Fibo-RR.txt
